### ISSUE TITLE
Plugin not compatible with Hogfather RC2

### ISSUE THREAD

**Issue by cschive** [ssahara/dw-plugin-NumberedHeadings#13]
Pages which use the plugin with === - chapter === format will not open. No error messages given in Firefox. Chrome gives a 500 error.

**Comment by phy25** [comment]
```
[Sat Jun 06 21:59:18.318683 2020] [php7:error] [pid 15524] [client ::1:32774] PHP Fatal error: Uncaught Error: Cannot access protected property Doku_Handler::$status in /var/www/dokuwiki/lib/plugins/numberedheadings/syntax.php:133\nStack trace:\n#0 /var/www/dokuwiki/inc/parser/handler.php(240): syntax_plugin_numberedheadings->handle('=== - Mixing ==...', 5, 3202, Object(Doku_Handler))\n#1 /var/www/dokuwiki/inc/Parsing/Lexer/Lexer.php(278): Doku_Handler->plugin('=== - Mixing ==...', 5, 3202, 'numberedheading...')\n#2 /var/www/dokuwiki/inc/Parsing/Lexer/Lexer.php(205): dokuwiki\\Parsing\\Lexer\\Lexer->invokeHandler('=== - Mixing ==...', 5, 3202)\n#3 /var/www/dokuwiki/inc/Parsing/Lexer/Lexer.php(155): dokuwiki\\Parsing\\Lexer\\Lexer->dispatchTokens('', '=== - Mixing ==...', '_plugin_numbere...', 3202, 3202)\n#4 /var/www/dokuwiki/inc/Parsing/Parser.php(109): dokuwiki\\Parsing\\Lexer\\Lexer->parse('\\n\\nMix bread flo...')\n#5 /var/www/dokuwiki/inc/parserutils.php(216): dokuwiki\\Parsing\\Parser->parse('\\n====== Banh mi...')\n#6 /var/www/dokuwiki/inc/parserutils.php(181): p_get_instructions('====== Banh mi ...')\n#7 /var/www/dok in /var/www/dokuwiki/lib/plugins/numberedheadings/syntax.php on line 133, referer: http://kochen.localhost/brot-rezepte/start
```

From @tracing-home. Should be fixed by https://github.com/splitbrain/dokuwiki/pull/3122.

**Comment by ssahara** [comment]
please see https://github.com/splitbrain/dokuwiki/issues/2931
